package com.auth0.jwt;

import java.security.SignatureException;
import java.util.Map;
import org.apache.commons.codec.binary.Base64;
import org.junit.Assert;
import org.junit.Test;

public class JWTVerifierRsaTest {
	private static final String SIGNED_DATA = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjUwMjE4MzE1In0.eyJhbnN3ZXIiOnsiYXV0aF9hdHRyaWJ1dGVzIjp7InRleHRfZmllbGRzIjpbXSwic3ViamVjdF9yZXBseSI6IlJlamVjdCJ9fSwiZGF0YSI6eyJhdXRoX2F0dHJpYnV0ZXMiOnsidGV4dF9ib3hlcyI6W10sInRpdGxlIjoiVGVzdCBtZXNzYWdlIiwiYnV0dG9ucyI6W3sibGFiZWwiOiJBY2NlcHQiLCJyb2xlIjoicG9zaXRpdmUiLCJmbGFncyI6W119LHsibGFiZWwiOiJSZWplY3QiLCJyb2xlIjoibmVnYXRpdmUiLCJmbGFncyI6W119XSwidmFsdWVfcGFpcnMiOltdLCJ0ZXh0IjoiVGhpcyBpcyBhIHRlc3QgbWVzc2FnZSJ9LCJ0aW1lc3RhbXAiOjE0MjEwNzEwMDMxNjksImF1dGhfaWQiOiIwODVmZGNiYi0xZGJhLTQ1NjYtYTk0Zi01NzYwM2NjMDU4ZDYiLCJhdXRoX3R5cGUiOiJhdXRoIiwic3ViamVjdF9pZCI6IjUwMjE4MzE1In19.n3l4kLwh7z5YdgLXr3Hdy6mi1qnM23JtzqN1G4vhYFuskTYiItv3XxUHyWHIh8wzIa6Y6UAm6oRllbZ8os6qDZu5gYVwNnezCxO9j8OICnbTZWsDRtnSsTfM8bUjFm4ZYAAWeB5an7lYyhX0BIMQtAEyb5jYL3Q-_CB3QwcbtgDRXw1qpOFCxT_VvJPsGlcCR--ReCDNgYgLB1DwgbzocI8QeNwdc41zD9CXea8zmrTO76wvcqN56IQuwasX0rDEcvlDxVJW1Qhg1oOH_1yBiIEjpcKgGVGcmqXE7luUY6Z8fM_t1IIXF8ZembjbwXWTMWKKFMFR5cvGKc8_6SX5rA";
	private static final String USER_CERT = "MIIEDTCCA3agAwIBAgIEAv5FSzANBgkqhkiG9w0BAQsFADA6MQswCQYDVQQGEwJaQTESMBAGA1UECgwJRW50ZXJzZWt0MRcwFQYDVQQDDA5EZXYgSVRBIERlbW8gMTAeFw0xNTAxMTEwMDAwMDBaFw0xNTA4MjAwMDAwMDBaMGoxCzAJBgNVBAYTAlpBMRwwGgYDVQQKDBNFbnRlcnNla3QgKFB0eSkgTHRkMSowKAYDVQQLDCFFbnRlcnNla3QgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxETAPBgNVBAMMCDUwMjE4MzE1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxCMFs6UBUr+RYneZwZfHRpw8Ictz18Cc8XvELtwB4kZinvrnpPnsaWNn6WkSuGqxOA/aqHP7DisbTZWJrfgeyzDox6uWyVjSkJ48h/6RKCan90wqJa98KCMdCHY8G+xqRb6g3JvZKeHHhLQg+nKjKW2P8QEkzxq1TwqtrE8qLavPRdTG0XH9Ow+BtvvMZv9B3Czno5jpEg2Hd2wS1FlVpEqqz3DD9+1y/bjcfC+6AgxEZl/nnNQj8eah5cYjK7zBKH41rCmDExmTKSqFa7PsyOrRy6X3WDUrRuvKY0J+8M3KQIGBqXCX7IeAuQvnY/BZfb+VrMVgHRwAOdSAVGDFrQIDAQABo4IBajCCAWYwDgYDVR0PAQH/BAQDAgPoMEUGA1UdHwQ+MDwwOqA4oDaGNGh0dHA6Ly9jYS5kZXYuZW50ZXJzZWN0LmNvLnphL2VjZXJ0MTUvY3JsLnBocD9zbj03ODMwPAYDVR0gBDUwMzAxBgNVHSAwKjAoBggrBgEFBQcCARYcaHR0cDovL3d3dy5lbnRlcnNla3QuY29tL2NwczATBgNVHSUEDDAKBggrBgEFBQcDAjAfBgNVHSMEGDAWgBSpi7r5Abd1W3WcjuXb3VRb5dGvEDAdBgNVHQ4EFgQUPKszj8XKI4xNWDvxsiEhqgaVqV4wEAYKKwYBBAGCqlsBBwQCBQAwEAYKKwYBBAGCqlsBCAQCBQAwFAYKKwYBBAGCqlsBBAQGAgQC/kVLMB8GCisGAQQBgqpbAQEEERgPMjAxNTA4MTkwMDAwMDBaMB8GCisGAQQBgqpbAQIEERgPMjAxNzAxMTMwMDAwMDBaMA0GCSqGSIb3DQEBCwUAA4GBAIGKCyYqjj4Mkkb0lPRil+ti3hevrF7Je/L3z+qlUNo4jqOMOrtiAalnYX5j5+0lmP8fXViQMy9Mo2MZcLM1RV556NOZiWrPmP/OYDKXPcLNCgWQfYcuu2hvUvVv0WQgIwBzFBuAPpvZn1MnShoEvoNOzrSOBWdGSycRjxP4DCpL";
	private static final String EXPECTED_SUBJECT_REPLY = "Reject";

	private static final String INVALID_SIGNED_DATA = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjkyOTgzMTgwIn0.eyJhbnN3ZXIiOnsiYXV0aF9hdHRyaWJ1dGVzIjp7InRleHRfZmllbGRzIjpbXSwic3ViamVjdF9yZXBseSI6IlJlamVjdCJ9fSwiZGF0YSI6eyJhdXRoX2F0dHJpYnV0ZXMiOnsidGV4dF9ib3hlcyI6W10sInRpdGxlIjoiVGVzdCBtZXNzYWdlIiwiYnV0dG9ucyI6W3sibGFiZWwiOiJBY2NlcHQiLCJyb2xlIjoicG9zaXRpdmUiLCJmbGFncyI6W119LHsibGFiZWwiOiJSZWplY3QiLCJyb2xlIjoibmVnYXRpdmUiLCJmbGFncyI6W119XSwidmFsdWVfcGFpcnMiOltdLCJ0ZXh0IjoiVGhpcyBpcyBhIHRlc3QgbWVzc2FnZSJ9LCJ0aW1lc3RhbXAiOjE0MjEwNzEwMDMxNjksImF1dGhfaWQiOiIwODVmZGNiYi0xZGJhLTQ1NjYtYTk0Zi01NzYwM2NjMDU4ZDYiLCJhdXRoX3R5cGUiOiJhdXRoIiwic3ViamVjdF9pZCI6IjUwMjE4MzE1In19.n3l4kLwh7z5YdgLXr3Hdy6mi1qnM23JtzqN1G4vhYFuskTYiItv3XxUHyWHIh8wzIa6Y6UAm6oRllbZ8os6qDZu5gYVwNnezCxO9j8OICnbTZWsDRtnSsTfM8bUjFm4ZYAAWeB5an7lYyhX0BIMQtAEyb5jYL3Q-_CB3QwcbtgDRXw1qpOFCxT_VvJPsGlcCR--ReCDNgYgLB1DwgbzocI8QeNwdc41zD9CXea8zmrTO76wvcqN56IQuwasX0rDEcvlDxVJW1Qhg1oOH_1yBiIEjpcKgGVGcmqXE7luUY6Z8fM_t1IIXF8ZembjbwXWTMWKKFMFR5cvGKc8_6SX5rA";
	private static final String INVALID_USER_CERT = "MIICtDCCAZygAwIBAgIEVLOfyTANBgkqhkiG9w0BAQsFADAcMQswCQYDVQQGEwJaQTENMAsGA1UEAwwEdGVzdDAeFw0xNTAxMTIxMDE5NTlaFw0xNjAxMTIxMDE5NTlaMBwxCzAJBgNVBAYTAlpBMQ0wCwYDVQQDDAR0ZXN0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn+S6j3sJ/WxAnWeN3kHBecMkjXq8RcswxrnJp2ok5gH/YeNlCRkhwQmMSPKqBy0ewswq5xAL3KPJjCZNRo8K03rRUTay9TJ7GcjdiUuhKXgXIXoB9wqNxMPZyGdgU/vZRTM3MWuuefyUUdajh/ucIQ8YBwvbfpx4x9ygvrh7finUBNT+gcr6r4+MA8M0eK2Z6wfRUx0fC1TExRMOpKTFJmgc2bnQE4uzNUv30+Ka1Zy/iT1WlDwoufA4q55wwkTkcYANq6O5sU8v6dWmaB9+Py/fpYkcqaABAoa2uBT9LalEO8g09LdcegELQ8WQwrNkmENUZPpMXR02ltkjlJkWgQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQAZH6RJn3qHKPs4SIbe4Z1mFo/i9XJ3Lm4O1rzFpnXhi79YcbNVQevQr3Q1qm1tatlvi7uwvQjJIzn4IUu/1Z9kKqdoSXwq5CUccKnZ4X40XIHa27jDXxeGl88jKNaf+MGE520/bYMHnNze+UI2RTdEuZcaPJtIM9KEoTk/J0wg1oUomGB1+An4sa+UgQ+sc06hu/kGevCVGQGKR6y7Hga/ZPYjIagWBDT0Q2Mx/UCiYNg/FfNg5XDZz69C1WhM4r9Y6+VnyGjGiCjty9OK8nXHlgjGGOLIGO73csuvE9S94bGRLMqgXZ/aCGetysk/Y162+tOE1KbkJzbx+7P082Vw";

	@Test
	public void shouldVerifySignature() throws Exception {
		byte[] decodedUserCert = Base64.decodeBase64(USER_CERT);
		JWTVerifier jwtVerifier = new JWTVerifier(decodedUserCert);
		Map<String, Object> data = jwtVerifier.verify(SIGNED_DATA);
		Map<String, Object> answer = (Map<String, Object>) data.get("answer");
		Map<String, Object> authAttributes = (Map<String, Object>) answer.get("auth_attributes");
		String subjectReply = (String) authAttributes.get("subject_reply");
		Assert.assertEquals(EXPECTED_SUBJECT_REPLY, subjectReply);
	}

	@Test(expected = SignatureException.class)
	public void shouldFailInvalidClaimset() throws Exception {
		byte[] decodedUserCert = Base64.decodeBase64(USER_CERT);
		JWTVerifier jwtVerifier = new JWTVerifier(decodedUserCert);
		jwtVerifier.verify(INVALID_SIGNED_DATA);
	}

	@Test(expected = SignatureException.class)
	public void shouldFailInvalidCert() throws Exception {
		byte[] decodedUserCert = Base64.decodeBase64(INVALID_USER_CERT);
		JWTVerifier jwtVerifier = new JWTVerifier(decodedUserCert);
		jwtVerifier.verify(SIGNED_DATA);
	}
}